### ISSUE TITLE
bug - can't type space in comments box

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#62]
I'm unable to use spaces in the comments box (tested using Chrome)
http://maps.nypl.org/warper/maps/14719#Comments_tab

**Comment by mgiraldo** [comment]
also on Firefox

**Comment by scspaeth** [comment]
I got a similar result using Firefox and discovered that it would not let me left-arrow back through text to revise what I had written.
http://maps.nypl.org/warper/maps/12966#Comments_tab

**Comment by mgiraldo** [comment]
yeah it is broken :\

**Comment by mgiraldo** [comment]
apparently it is related to jQuery UI tabs being used. it allows users to move from tab to tab using arrows (it is somewhat broken, though) and other widgets make use of the spacebar

i'm not a fan of jQuery UI, but not sure what will break by removing it (the tabs will surely break, i suppose)

it _used_ to work, though, since [some comments do have spaces](http://maps.nypl.org/warper/maps/14719#Comments_tab) (maybe related to recent keyboard navigation improvements?)

**Comment by lklepner** [comment]
It appears to be related to the OpenLayers keyboard controls. 

This was confirmed by reverting to a commit prior to enabling the keyboard controls and it works correctly. 

I can look into resolving it towards the end of the week.

**Comment by mgiraldo** [comment]
fixed in b2ab6f321178aa12344623454481b757c92fdc39
